--SQL code SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS basketball DEFAULT CHARACTER SET utf8;
USE basketball;

-- Table basketball.teams
DROP TABLE IF EXISTS basketball.teams;

CREATE TABLE IF NOT EXISTS basketball.teams (
team_id INT(70) NOT NULL AUTO_INCREMENT,
name VARCHAR(45) NOT NULL,
logo VARCHAR(45) NULL,
created_date TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (team_id),
UNIQUE INDEX team_name_UNIQUE (name ASC))
ENGINE = InnoDB;
